### PR TITLE
Web catalog generator [WIP]

### PR DESCRIPTION
**Pull request by mih**
A trial for implementing a generator for a dataset web catalog. In contrast to the existing web-UI (see http://datasets.datalad.org), it aims to provide a dataset-centric view. A primary purpose for this is to have google index the datasets (https://github.com/datalad/datalad/issues/2793).

This change sits on top of https://github.com/datalad/datalad-revolution/pull/75 and uses this as a source for appropriate google-compatible metadata.

There is a test deployment at http://playground.ipsymd.de (thx @aqw) to check whether the googlebot is able to pick up structured metadata that is dynamically gathered upon request. If this test fails, such a web catalog either has to be dynamically served by a server-side component, or the generator needs to craft all html files. Both solutions are inferior IMHO.

Test failures can be ignored for now, until the core concept is verified to work. Which will be clear, if something shows up here: https://toolbox.google.com/datasetsearch/search?query=datalad
Metadata sanity is already checked: https://search.google.com/structured-data/testing-tool/u/0/#url=http%3A%2F%2Fplayground.ipsymd.de%2F

The reason for this to be in -revolution is that path handling via pathlib is sooo much easier...

- [x] export sitemap.xml for google
- [x] rename sitemap file to make naming conflict less likely
- [ ] issue message to include sitemap file location in robots.txt (so google can find it), or info that a sitemap needs to be submitted

### CODE REVIEW

**Comment by mih** [comment]
URL is not indexed, but dataset does not (yet) show up in search, as of today. Today, I also submitted a sitemap.xml to Google. Maybe that helps.

**Comment by mih** [comment]
We are now indexed!!!!

**Comment by yarikoptic** [comment]
Awesome! People now will find the hot dog of the day! We should see what it would take to produce and update such info at datasets.datalad.Org

**Comment by mih** [comment]
Closing this now, as it no longer serves a purpose here. A similar PR will resurface at https://github.com/datalad/datalad-metalad

**Pull request closed without merging**
