### PR TITLE
RF: relative imports

### PR DESCRIPTION
**Pull request by yarikoptic**
all commits are the `datalad run` commits so later could be repeated on the new codebase

### CODE REVIEW

**Comment by kyleam** [comment]
> all commits are the `datalad run` commits

without custom messages :/

**Comment by yarikoptic** [comment]
> > all commits are the `datalad run` commits
> 
> without custom messages :/

kinda on purpose since they are intended (if not truncated that soon) self descriptive. Otherwise it would be just the same but in less precise/descriptive human language

**Comment by kyleam** [comment]
> kinda on purpose since they are intended (if not truncated that soon) self descriptive.

I would dislike it if the summary line were allowed to be longer, but either way, they *are* truncated so it doesn't make much sense to me to avoid using a custom message because they *would* be more descriptive if not truncated.

> Otherwise it would be just the same but in less precise/descriptive human language.

In my view the command is too long to be a reasonable summary, and it is present in the message body  for those who want the precision.  I would rather have less precise language in the summary line that gives me an overall all sense of what the change is about.

And nothing forbids providing more information in a custom body, but the fact that datalad doesn't support popping into an editor does make doing so inconvenient.

**Comment by yarikoptic** [comment]
ok, I will keep it in mind for the future. Actually just did -- in the https://github.com/datalad/datalad/pull/3076/commits you will see some with proper messages

**Comment by kyleam** [comment]
> ok, I will keep it in mind for the future. Actually just did -- in the https://github.com/datalad/datalad/pull/3076/commits you will see some with proper messages

My two cents feel so heavy :]

**Comment by yarikoptic** [comment]
ok, no objections, tests pass, merging

**Pull request merged**
