### PR TITLE
ENH(BK): relative imports start again

### PR DESCRIPTION
**Pull request by yarikoptic**
Originally RFed in #60 

- [ ] Travis - fail if any absolute import left
- [x] Fix absolute imports -- will come after first commit is shown to fail the travis

### CODE REVIEW

**Comment by yarikoptic** [comment]
hm, @mih @bpoldrack any ideas why travis isn't running? don't even see it among https://travis-ci.org/datalad/datalad-revolution/pull_requests

**Comment by bpoldrack** [comment]
Found it here:
https://travis-ci.org/datalad/datalad-revolution/requests

And it reads "Could not parse .travis.yml" - no additional info. Looking at it: What is this `|| :`? Some magic, I don't know or a typo?

**Comment by yarikoptic** [comment]
ha - I was afraid it would ruin it.. will fix now -- thanks @bpoldrack !!!!

**Comment by yarikoptic** [comment]
Only some installation error, restarted the build, but since others pass, consider it done

**Pull request merged**
