### PR TITLE
Next-level metadata

### PR DESCRIPTION
**Pull request by mih**
Prompted by a few realizations I had while working on #118

- [x] any extractor can now report metadata records on multiple entities (not just datasets and files). It can simply report metadata using JSON-LD graphs documents (`{"@content": {}, "@graph": []}`) with as many nodes as desired, using whatever `@type` to identifier the nature of the described entity
- [x] rev-extract-metadata can now report a single JSON-LD object with ALL linked metadata on anything in a dataset
- [x] there is no longer a "refcommit" field in the core metadata. This is used for `@id` now. The dataset UUID is now in `identifier`
- [x] `--reporton jsonld` for `query-metadata`
- [x] Consider RF to determine the refcommit upfront and provide extractors this value as a readily usable ID. Without it, we are implicitly limitation JSON-LD reports to a single dataset-type document (to assign an ID to). Hence any extractor could not talk about two datasets, one of which is just described in order to document a particular relationship. This would break the promise of "any output works".

### CODE REVIEW

**Comment by yarikoptic** [comment]
> there is no longer a "refcommit" field in the core metadata. This is used for @id now.

Couldn't there be a collision of some kind of someone else decides to also (an)use git commit for the `@id`?

**Comment by mih** [comment]
> Couldn't there be a collision of some kind of someone else decides to also (an)use git commit for the @id?

Re-use of this kind would be intentional, and desirable. The ID identifies the thing that is being described. Any extractor describing the dataset should use this ID (across any number of JSON-LD documents). This way, any property reported by any extractor becomes a property of the graph node that represents the dataset. A collision of other kinds is extremely unlikely, it is a Git SHA of a commit after all.

**Comment by yarikoptic** [comment]
> Re-use of this kind would be intentional, and desirable. The ID identifies the thing that is being described.

just for my own clarity: I understand that if two of our records for the dataset have that unique id - we are good.  But by collision I meant, e.g., if I have some custom extractor and also decided to give repo's shasum as `@id` -- wouldn't then it collide with our dataset record?  So what I mean, is `@id` considered together with some other namespace (eg. `datalad`) or independently by itself?  if by itself, then we could get collision with some other records where similarly bright minds decided to use git checksum for the `@id`.  One way to disambiguate could be to prefix or suffix that `@id` with something datalad specific then may be?

**Comment by mih** [comment]
> just for my own clarity: I understand that if two of our records for the dataset have that unique id - we are good.

Yes.

> But by collision I meant, e.g., if I have some custom extractor and also decided to give repo's shasum as @id -- wouldn't then it collide with our dataset record?

No. Documents with the same ID never replace each other, they amend each other.

> So what I mean, is @id considered together with some other namespace (eg. datalad) or independently by itself? if by itself, then we could get collision with some other records where similarly bright minds decided to use git checksum for the @id. One way to disambiguate could be to prefix or suffix that @id with something datalad specific then may be?

There is no need for prefixes, and there is no namespace other than the global namespace. JSON-LD uses terms that are uniquely defined. Let's say we have two documents with the same '@id'. This means they must be talking about the same thing. If both define 'name', via `name=some` and `name=other`, then those become `name=[some, other]` in the ultimately metadata graph node, reflecting the fact that the same thing has two different names attributed to it. If these two specifications of "name" do not have the same meaning, they cannot be using the same term. This can be achieved by assigning a different term (url) via a different JSON-LD context. This is fine, does not conflict with our internal structure or the way we are reporting this back out.

**Comment by yarikoptic** [comment]
ah, cool, thanks for the explanation!

**Pull request merged**
